## Numpy
> Vectorizing with numpy

In [1]:
!pip install numpy -qU


[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: python3.10 -m pip install --upgrade pip


##### numpy
<pre>
    - scientific computing pkg
    - supports n-dimentional homogeneous(same types) array
    - fast
    - broadcasting (implicit element-by-element behavior of operations)
</pre>

In [2]:
import numpy as np

In [4]:
## create numpy arr
narr = np.array([[12, 23, 34], [32, 21, 88]])
print(f"narr --> {narr}") # numpy array
print(f"ndim --> {narr.ndim}") # dimention of arr
print(f"shape --> {narr.shape}") # tuple with (n, m) row col
print(f"dtype --> {narr.dtype}") # data type 
print(f"size --> {narr.size}") # total number of elements of the arr
print(f"itemsize --> {narr.itemsize}") # size in bytes of each element

narr --> [[12 23 34]
 [32 21 88]]
ndim --> 2
shape --> (2, 3)
dtype --> int64
size --> 6
itemsize --> 8


In [6]:
## create numpy arr with range
narr_2 = np.arange(12).reshape(3, 4)
narr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
## arr with zeros
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
## arr with ones
np.ones((2, 3, 4), dtype=np.float16)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)

In [10]:
## arr with random numbers
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
## range arr
np.arange(2.1, 3.1, 0.2) # start, end, step

array([2.1, 2.3, 2.5, 2.7, 2.9])

In [12]:
## as it is difficult to predict numbers generated with arange step
## linspace generates the numbers from arg
np.linspace(1.10, 2.10, 7) # 7 numbers from 1.10 to 2.10 

array([1.1       , 1.26666667, 1.43333333, 1.6       , 1.76666667,
       1.93333333, 2.1       ])

#### Basic operations

In [13]:
## arithmatic
a = np.array([11, 22, 33])
b = np.arange(3)

In [14]:
print(a)
print("-"*10)
print(b)

[11 22 33]
----------
[0 1 2]


In [15]:
print(f"a-b: {a-b}")
print(f"a+b: {a+b}")
print(f"b**2: {b**2}")
print(f"a < 12: {a<12}")
print(f"mul: {10 * np.sin(a)}")

a-b: [11 21 31]
a+b: [11 23 35]
b**2: [0 1 4]
a < 12: [ True False False]
mul: [-9.99990207 -0.08851309  9.9991186 ]


In [16]:
## matrix operations
aa = np.array([[1, 1], [0, 0]])
bb = np.array([[2, 1], [1, 2]])

print(f"aa*bb: {aa*bb}") # elementwise product
print(f"aa@bb: {aa@bb}") # matrix product
print(f"aa.bb: {aa.dot(bb)}") # dot product

aa*bb: [[2 1]
 [0 0]]
aa@bb: [[3 3]
 [0 0]]
aa.bb: [[3 3]
 [0 0]]


In [17]:
## operations on axis
print(f"{narr_2}")
print(f"sum_0: {narr_2.sum(axis=0)}") # sum of axis 0 (col)
print(f"sum_1: {narr_2.sum(axis=1)}") # sum of axis 1 (row)
print(f"min: {narr_2.min(axis=0)}") # min of axis 0
print(f"max: {narr_2.max(axis=0)}") # max of axis 0

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum_0: [12 15 18 21]
sum_1: [ 6 22 38]
min: [0 1 2 3]
max: [ 8  9 10 11]


In [19]:
## indexing and slicing
narr = np.arange(8)**2
print(f"{narr}")
print(f"narr[2]: {narr[2]}")
print(f"narr[3:6]: {narr[3:6]}")
print(f"narr[::-1]: {narr}") # reversed narr
print(f"narr[-1]: {narr}") # last element

[ 0  1  4  9 16 25 36 49]
narr[2]: 4
narr[3:6]: [ 9 16 25]
narr[::-1]: [ 0  1  4  9 16 25 36 49]
narr[-1]: [ 0  1  4  9 16 25 36 49]


In [20]:
## multidimensional arr have one index per axis
## create arr fromfunction
def farr(r, c):
    return 10 * r +c

b = np.fromfunction(farr, (3, 5), dtype=int)
print(f"b: {b}")
print(f"b[2,3]: {b[2, 3]}")
print(f"b[0:5, 1]: {b[0:5, 1]}") # row in c at index 1
print(f"b[2:4, :]: {b[2:4, :]}") # col in r at index 2 and 4

b: [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
b[2,3]: 23
b[0:5, 1]: [ 1 11 21]
b[2:4, :]: [[20 21 22 23 24]]


In [21]:
print(b[1, ...]) # same as b[1, :, :] or b[1]
print(b[..., 2]) # same as b[:, :, 2] 

[10 11 12 13 14]
[ 2 12 22]


In [32]:
## shape
## reshape : arr with modified shape
print(f"b shape: {b.shape}")
print(f"flatten: {b.ravel()}") # flatten arr
print(f"reshape: {b.reshape(5, 3)}") # reshape (use -1 as other dim if not want to calculate)
print(f"transpose: {b.T.shape}") # transpose shape

## resize: modifies arr itself
print(f"resize: {b.resize((3, 5))}")

b shape: (3, 5)
flatten: [ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24]
reshape: [[ 0  1  2]
 [ 3  4 10]
 [11 12 13]
 [14 20 21]
 [22 23 24]]
transpose: (5, 3)
resize: None


In [33]:
## after resize
b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [35]:
## stacking arr
print(f"vstack: {np.vstack((aa, bb))}") # |
print(f"hstack: {np.hstack((aa, bb))}") # -

vstack: [[1 1]
 [0 0]
 [2 1]
 [1 2]]
hstack: [[1 1 2 1]
 [0 0 1 2]]


In [39]:
## splitting arr into smaller ones
print(np.hsplit(b, 1)) # b into 1
print(np.hsplit(b, (2, 3))) # after 2 and 3 col

[array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])]
[array([[ 0,  1],
       [10, 11],
       [20, 21]]), array([[ 2],
       [12],
       [22]]), array([[ 3,  4],
       [13, 14],
       [23, 24]])]


In [40]:
## shallow copy or view
## create new arr obj at same data
c = b.view()
print(c is b) # F as c is shallow copy of b, not b itself
print(c.base is b) # T as c points at same data as b
print(c.reshape(15, 1)) # does not change shape of b
print(b.shape)

False
True
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [10]
 [11]
 [12]
 [13]
 [14]
 [20]
 [21]
 [22]
 [23]
 [24]]
(3, 5)


In [41]:
c[0,0] = 4545 
b
## changes b data

array([[4545,    1,    2,    3,    4],
       [  10,   11,   12,   13,   14],
       [  20,   21,   22,   23,   24]])

In [42]:
## to avoid this use deepcopy
d = b.copy() # create new arr with new data
print(d is b) # F as it is new arr itself
print(d.base is b) # F (also)

False
False


In [44]:
d[0, 0] = 3232
print(f"{b=}")
## dose not change b as d and b are two diff arr
print(f"{d=}")

b=array([[4545,    1,    2,    3,    4],
       [  10,   11,   12,   13,   14],
       [  20,   21,   22,   23,   24]])
d=array([[3232,    1,    2,    3,    4],
       [  10,   11,   12,   13,   14],
       [  20,   21,   22,   23,   24]])
